// Objective-C API for talking to wallet_sdk/wallet Go package.
//   gobind -lang=objc wallet_sdk/wallet
//
// File is generated by gobind. Do not edit.

#ifndef __Wallet_H__
#define __Wallet_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class WalletWallet;

@interface WalletWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * 通过钱包种子创建一个SDK钱包
 */
- (nullable instancetype)init:(NSData* _Nullable)seed;
- (nullable instancetype)initForMobile:(NSString* _Nullable)seed;
/**
 * 钱包广播交易
 */
- (NSString* _Nonnull)broadcast:(NSString* _Nullable)coin signedResult:(NSData* _Nullable)signedResult error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)broadcastForMobile:(NSString* _Nullable)coin signedResult:(NSString* _Nullable)signedResult error:(NSError* _Nullable* _Nullable)error;
/**
 * 钱包根据币种和编号推导出账户地址
 */
- (NSString* _Nonnull)deriveAddress:(NSString* _Nullable)coin seq:(int64_t)seq error:(NSError* _Nullable* _Nullable)error;
/**
 * 钱包导出账户私钥
 */
- (NSString* _Nonnull)exportAddressPrivateKey:(NSString* _Nullable)coin seq:(long)seq error:(NSError* _Nullable* _Nullable)error;
/**
 * 获取钱包的节点URL
 */
- (NSString* _Nonnull)nodeUrl:(NSString* _Nullable)coin error:(NSError* _Nullable* _Nullable)error;
- (BOOL)setHttpPublicKeysPath:(NSString* _Nullable)coin path:(NSString* _Nullable)path error:(NSError* _Nullable* _Nullable)error;
/**
 * 设置钱包的节点URL
 */
- (BOOL)setNodeUrl:(NSString* _Nullable)coin url:(NSString* _Nullable)url error:(NSError* _Nullable* _Nullable)error;
// skipped method Wallet.Sign with unsupported parameter or return types

- (NSString* _Nonnull)signForMobile:(NSString* _Nullable)coinName seq:(int64_t)seq tx:(NSString* _Nullable)tx error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * 查看sdk是否支持该币种
 */
FOUNDATION_EXPORT BOOL WalletCoinIsSupport(NSString* _Nullable coin);

/**
 * 通过128-256字节的熵值创建返回一个随机生成的BIP-39助记词
 */
FOUNDATION_EXPORT NSString* _Nonnull WalletNewMnemonic(long bits, NSError* _Nullable* _Nullable error);

/**
 * 通过助记词和密码口令生成钱包种子
 */
FOUNDATION_EXPORT NSData* _Nullable WalletNewSeed(NSString* _Nullable mnemonic, NSString* _Nullable password, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull WalletNewSeedForMobile(NSString* _Nullable mnemonic, NSString* _Nullable password, NSError* _Nullable* _Nullable error);

/**
 * 通过钱包种子创建一个SDK钱包
 */
FOUNDATION_EXPORT WalletWallet* _Nullable WalletNewWallet(NSData* _Nullable seed, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT WalletWallet* _Nullable WalletNewWalletForMobile(NSString* _Nullable seed, NSError* _Nullable* _Nullable error);

#endif
